basePath: /
definitions:
  utils.FailureAuthResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
  utils.SuccessAuthResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
      token:
        type: string
    type: object
  utils.SuccessResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
  utils.SwaggerUserRegister:
    properties:
      city:
        type: string
      country:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        maxLength: 500
        minLength: 6
        type: string
      phone_number:
        type: string
      street:
        type: string
      zip_code:
        type: string
    required:
    - city
    - country
    - email
    - first_name
    - last_name
    - password
    - phone_number
    - street
    - zip_code
    type: object
host: localhost:8080
info:
  contact: {}
  title: E-Commerce API
  version: "1.0"
paths:
  /auth/change-password:
    post:
      consumes:
      - application/json
      parameters:
      - default: Bearer Token
        description: '`Bearer Token`'
        in: header
        name: authorization
        required: true
        type: string
      - description: Old Password
        in: body
        name: old_password
        required: true
        schema:
          type: string
      - description: New Password
        in: body
        name: new_password
        required: true
        schema:
          type: string
      - description: New Password Confirm
        in: body
        name: new_password_confirm
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "415":
          description: Unsupported Media Type
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
      security:
      - BearerAuth: []
      summary: Change user password
      tags:
      - User
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessAuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "415":
          description: Unsupported Media Type
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
      summary: Login a user
      tags:
      - User
  /auth/logout:
    post:
      consumes:
      - application/json
      parameters:
      - default: Bearer Token
        description: '`Bearer Token`'
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
      security:
      - BearerAuth: []
      summary: Logout a user
      tags:
      - User
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Data
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/utils.SwaggerUserRegister'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.SuccessAuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "415":
          description: Unsupported Media Type
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
      summary: Register a new user
      tags:
      - User
  /auth/verify-phone:
    post:
      consumes:
      - application/json
      parameters:
      - default: Bearer Token
        description: '`Bearer Token`'
        in: header
        name: authorization
        required: true
        type: string
      - description: Phone Verification Code
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "415":
          description: Unsupported Media Type
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.FailureAuthResponse'
      security:
      - BearerAuth: []
      summary: Verify user phone
      tags:
      - User
swagger: "2.0"
